apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nats
  namespace: project
spec:
  interval: 5m0s
  url: https://nats-io.github.io/k8s/helm/charts/

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-nats
  namespace: project
spec:
  interval: 5m
  chart:
    spec:
      chart: nats
      version: 0.17.5
      sourceRef:
        kind: HelmRepository
        name: nats
        namespace: project
      interval: 5m0s